import type { CategoryDefinition } from "./types";

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: "electromenager",
    name: "Gros electromenager",
    icon: "🏠",
    subs: [
      { id: "lave-linge", name: "Lave-linge", icon: "🫧" },
      { id: "seche-linge", name: "Seche-linge", icon: "🌬️" },
      { id: "lave-vaisselle", name: "Lave-vaisselle", icon: "🍽️" },
      { id: "frigos-top", name: "Refrigerateurs top", icon: "🧊" },
      { id: "frigos-1-porte", name: "Refrigerateurs 1 porte", icon: "🧊" },
      { id: "frigos-combines", name: "Refrigerateurs combines", icon: "🧊" },
      { id: "refrigerateurs-americains", name: "Refrigerateurs americains", icon: "🧊" },
      { id: "multi-door", name: "Multi-door", icon: "🚪" },
      { id: "congelateurs-armoire", name: "Congelateurs armoire", icon: "🥶" },
      { id: "congelateurs-coffre", name: "Congelateurs coffre", icon: "🧱" },
      { id: "fours-encastrables", name: "Fours encastrables", icon: "🔥" },
      { id: "micro-ondes", name: "Micro-ondes", icon: "♨️" },
      { id: "plaques-induction", name: "Plaques a induction", icon: "🍳" },
      { id: "plaques-vitroceramiques", name: "Plaques vitroceramiques", icon: "🍳" },
      { id: "cuisinieres", name: "Cuisinieres", icon: "🍳" },
      { id: "hottes", name: "Hottes", icon: "💨" },
      { id: "caves-a-vin", name: "Caves a vin", icon: "🍷" },
    ],
  },
  {
    id: "petit-electromenager",
    name: "Petit electromenager",
    icon: "☕",
    subs: [
      { id: "machines-expresso", name: "Machines expresso", icon: "☕" },
      { id: "cafetieres-filtre", name: "Cafetieres filtre", icon: "☕" },
      { id: "bouilloires", name: "Bouilloires", icon: "🫖" },
      { id: "grille-pain", name: "Grille-pain", icon: "🍞" },
      { id: "friteuses-air", name: "Friteuses a air", icon: "🍟" },
      { id: "robots-patissiers", name: "Robots patissiers", icon: "🥣" },
      { id: "blenders", name: "Blenders", icon: "🥤" },
      { id: "mixeurs-plongeants", name: "Mixeurs plongeants", icon: "🥄" },
      { id: "multicuiseurs", name: "Multicuiseurs", icon: "🍲" },
      { id: "aspirateurs-traineaux", name: "Aspirateurs traineaux", icon: "🧹" },
      { id: "aspirateurs-balais", name: "Aspirateurs balais", icon: "🧹" },
      { id: "aspirateurs-robots", name: "Aspirateurs robots", icon: "🤖" },
      { id: "nettoyeurs-vapeur", name: "Nettoyeurs vapeur", icon: "💨" },
      { id: "fers-a-repasser", name: "Fers a repasser", icon: "👔" },
      { id: "centrales-vapeur", name: "Centrales vapeur", icon: "👔" },
      { id: "seche-cheveux", name: "Seche-cheveux", icon: "💇" },
      { id: "lisseurs", name: "Lisseurs", icon: "💇" },
      { id: "tondeuses", name: "Tondeuses", icon: "✂️" },
      { id: "brosses-a-dents", name: "Brosses a dents electriques", icon: "🪥" },
      { id: "epilateurs", name: "Epilateurs", icon: "✨" },
    ],
  },
  {
    id: "televiseurs",
    name: "Televiseurs",
    icon: "📺",
    subs: [
      { id: "oled", name: "TV OLED", icon: "📺" },
      { id: "qled", name: "TV QLED", icon: "📺" },
      { id: "mini-led", name: "TV Mini LED", icon: "📺" },
      { id: "tv-4k", name: "TV 4K", icon: "📺" },
      { id: "tv-8k", name: "TV 8K", icon: "📺" },
      { id: "tv-gaming", name: "TV gaming", icon: "🎮" },
      { id: "videoprojecteurs", name: "Videoprojecteurs", icon: "🎬" },
      { id: "barres-de-son", name: "Barres de son", icon: "🔊" },
    ],
  },
  {
    id: "telephonie",
    name: "Telephonie",
    icon: "📱",
    subs: [
      { id: "smartphones", name: "Smartphones", icon: "📱" },
      { id: "tablettes", name: "Tablettes", icon: "📲" },
      { id: "montres-connectees", name: "Montres connectees", icon: "⌚" },
      { id: "ecouteurs", name: "Ecouteurs et audio nomade", icon: "🎧" },
    ],
  },
  {
    id: "informatique",
    name: "Informatique",
    icon: "💻",
    subs: [
      { id: "ordinateurs-portables", name: "Ordinateurs portables", icon: "💻" },
      { id: "ordinateurs-bureau", name: "Ordinateurs de bureau", icon: "🖥️" },
      { id: "pc-gaming", name: "PC gaming", icon: "🖱️" },
      { id: "ecrans", name: "Ecrans", icon: "🖥️" },
      { id: "imprimantes", name: "Imprimantes", icon: "🖨️" },
      { id: "composants", name: "Composants", icon: "🧩" },
      { id: "stockage", name: "Stockage", icon: "💾" },
      { id: "reseau", name: "Reseau", icon: "📶" },
    ],
  },
  {
    id: "jeux-video",
    name: "Jeux video",
    icon: "🎮",
    subs: [
      { id: "consoles", name: "Consoles", icon: "🎮" },
      { id: "jeux", name: "Jeux", icon: "🕹️" },
      { id: "accessoires-gaming", name: "Accessoires gaming", icon: "🎧" },
      { id: "simulation", name: "Simulation et volants", icon: "🏎️" },
    ],
  },
];

export function getCategoryIcon(category: string) {
  return CATEGORIES.find((item) => item.id === category)?.icon || "📦";
}
